### Listar todos os usuarios

GET http://localhost:8080/api/usuario
Accept: application/json

###

### Cadastrar novo usuario

POST http://localhost:8080/api/usuario
Content-Type: application/json

{
      "nome": "Fulano 2",
      "email": "fulano2@email.com",
      "telefone": "84111111115",
      "cpf":"111.111.111-11",
      "endereco": "Rua 1, bairro 1, cidade 1",
      "data_nascimento": "1991-01-01",
      "senha":"11111112",
      "status": "ativo"
}

###

### Deletar usuario

DELETE  http://localhost:8080/api/usuario/2
Accept: application/json

###

### Editando usuario

PUT  http://localhost:8080/api/usuario/1
Content-Type: application/json

{     
    "nome": "Fulano 1 editado",
    "email": "fulano2editado@email.com",
    "telefone": "84111111112",
    "cpf": "111.111.111-12",
    "endereco": "Rua 2, bairro 2, cidade 2",
    "data_nascimento": "1991-01-01T00:00:00.000Z",
    "senha": "11111111",
    "status": "ativo"
}

###

### Deletar todos usuarios

DELETE  http://localhost:8080/api/usuario

###